version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: auth_postgres
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: auth_db
    ports:
      - "5436:5432" # Externo:Interno
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
